export const SITE = 'https://www.argusshipping.co';
const service = (slug, label, h1, keyword, intro, sections, keywords, related, evidence) => ({
  path: `/services/${slug}-qatar/`, group: 'services', label, h1, keyword, intro, sections,
  title: `${label} in Qatar | Argus Shipping`,
  description: `${intro.split('. ')[0]}. Discuss your cargo and request a tailored quote from Argus Shipping.`,
  keywords: keywords.split('; '), related, evidence, priority: ['project-cargo', 'vehicle-logistics'].includes(slug) ? 'P3' : 'P1',
});
const s = (heading, text) => ({ heading, text });
export const servicePages = [
  service('air-freight', 'Air Freight Services', 'Air Freight Services in Qatar', 'air freight Qatar',
    'Argus Shipping coordinates international air freight for businesses importing to and exporting from Qatar. Share your cargo dimensions, weight and required delivery date so the team can assess a suitable air cargo option.', [
      s('International air cargo: import and export', 'Air freight suits shipments where the required arrival date matters more than the lowest transport cost. Argus coordinates origin handling, air transport and destination delivery requirements. Specify whether your quote should cover airport-to-airport movement or include collection and final delivery.'),
      s('Urgent and time-sensitive shipments', 'For an urgent consignment, send the cargo-ready date, origin address and delivery deadline before booking. Flight capacity, cargo acceptance and handling cut-offs affect the available schedule. A requested deadline is assessed shipment by shipment; it is not a guaranteed transit time.'),
      s('Cargo preparation and handling', 'Provide a packing list, cargo description, gross weight and dimensions for each package. Tell the team about batteries, liquids, fragile goods or other special handling needs before collection so acceptance and packaging can be checked. Do not dispatch restricted cargo before the proposed handling arrangement is confirmed.'),
      s('Airport handling, customs and delivery', 'Agree the collection point, export documentation responsibilities and Qatar delivery address when requesting a quote. Customs support and onward transport can be coordinated as part of the shipment scope. The team can explain which legs are included and which charges remain outside the freight quotation.'),
    ], 'air freight services Qatar; air cargo Qatar; air cargo services Qatar; air freight company Qatar; air freight forwarding Qatar; international air freight Qatar; air freight Doha; air cargo Doha; air freight forwarder Qatar; airport cargo Qatar; air import Qatar; air export Qatar; door-to-door air freight Qatar; urgent air freight Qatar; international air freight company Qatar; commercial air cargo Qatar; urgent cargo shipping Qatar',
    ['door-to-door-cargo', 'customs-clearance', 'sea-freight'], 'Services.jsx: air freight operations and airport-to-door support'),
  service('sea-freight', 'Sea Freight Services', 'Sea Freight Services in Qatar', 'sea freight Qatar',
    'Argus Shipping arranges FCL and LCL sea freight for Qatar importers and exporters. The service connects international cargo movements with origin coordination, customs support and delivery planning.', [
      s('FCL container shipping', 'Full Container Load is an option when a shipment requires a container dedicated to one shipper. Share the cargo volume, weight, package sizes and loading arrangements so container suitability can be reviewed. Container selection depends on the goods and their loading requirements, not volume alone.'),
      s('LCL consolidation services', 'Less than Container Load allows smaller consignments to share container capacity. Cargo must be received and handled through consolidation facilities at origin and destination. Compare the complete collection-to-delivery quotation, including handling, when choosing between LCL and FCL.'),
      s('Import and export through Hamad Port', 'For Qatar sea freight, the team coordinates the proposed origin gateway, ocean movement and destination handling. Confirm the actual vessel routing, any transshipment and cargo-ready date before booking. Delivery planning should allow for release formalities and the receiving site’s access arrangements.'),
      s('From supplier collection to final delivery', 'Send supplier details, a packing list and commercial shipment information with your enquiry. Argus can coordinate collection and door-to-door requirements alongside ocean freight. Warehousing can be discussed when cargo arrives before the receiving site is ready.'),
    ], 'sea freight services Qatar; ocean freight Qatar; ocean freight services Qatar; sea cargo Qatar; sea freight company Qatar; sea freight forwarder Qatar; container shipping Qatar; FCL shipping Qatar; LCL shipping Qatar; FCL freight Qatar; LCL freight Qatar; Hamad Port freight; sea freight Doha; import container Qatar; export container Qatar; FCL container shipping Qatar; ocean freight company Qatar; sea cargo import Qatar',
    ['customs-clearance', 'warehousing', 'door-to-door-cargo'], 'Services.jsx: sea freight, FCL/LCL and Hamad Port trade-lane table'),
  service('road-freight', 'Road Freight Services', 'Road Freight Services in Qatar & Across the GCC', 'road freight Qatar',
    'Argus Shipping coordinates road freight in Qatar and across the GCC. Businesses can discuss full-truckload and shared-load movements for factory, warehouse and consignee deliveries.', [
      s('Local collection and commercial delivery', 'Collection and delivery planning starts with the cargo size and the access available at each site. Provide loading equipment details, appointment windows and any unloading restrictions. These details help the team match the transport arrangement to the consignment.'),
      s('FTL and LTL freight', 'Full Truck Load provides a vehicle allocation for the shipment, while Less than Truck Load combines consignments within a shared movement. The choice depends on cargo volume, handling compatibility and delivery requirements. Ask for a scope that includes the intended loading and unloading responsibilities.'),
      s('GCC cross-border transportation', 'Regional freight requires coordination of origin collection, border formalities and final delivery. Argus’s network includes UAE-to-Qatar movements and GCC transport. The operating route and timing are confirmed against current cargo and border requirements rather than a fixed published promise.'),
      s('Plan the handover before dispatch', 'Share the collection location, consignee details, cargo description and supporting commercial documents. Identify equipment or fragile goods requiring particular securing arrangements. Customs support should be coordinated before the vehicle departs to reduce avoidable document queries.'),
    ], 'land freight Qatar; land transportation Qatar; road transportation Qatar; GCC road freight; cross-border freight Qatar; trucking company Qatar; cargo transport Qatar; GCC cargo transportation; FTL Qatar; LTL Qatar; Qatar UAE road freight; Qatar Saudi freight',
    ['customs-clearance', 'door-to-door-cargo', 'warehousing'], 'Services.jsx: GCC FTL/LTL and UAE/Saudi/Oman table'),
  service('warehousing', 'Warehousing & Storage', 'Warehousing & Storage Services in Qatar', 'warehousing services Qatar',
    'Argus Shipping provides warehousing and inventory support for commercial cargo. Discuss the storage period, stock profile and dispatch requirements to plan storage alongside freight and distribution.', [
      s('Commercial storage requirements', 'Storage planning depends on the goods, packaging, pallet or carton quantities and expected dwell time. Share how stock will arrive and whether it will be released as full pallets, cartons or individual orders. Handling needs should be agreed before goods are delivered to the warehouse.'),
      s('Inventory receipt and release', 'Accurate receiving information connects physical stock to the shipper’s records. Provide product references and quantities, identify any batch or serial tracking needs, and agree a release instruction process. This helps distinguish stock held for later delivery from goods ready for immediate dispatch.'),
      s('Warehousing connected to transport', 'Storage can bridge the gap between an international arrival and the consignee’s receiving schedule. Argus can discuss onward transport and distribution as part of the arrangement. For ongoing order handling and outsourced distribution, explore the separate 3PL service.'),
      s('Confirm storage conditions', 'Tell the team about temperature, security, segregation or other product-specific requirements at the enquiry stage. Facility suitability, capacity and any required controls must be confirmed for the actual cargo before booking.'),
    ], 'warehousing Qatar; warehouse Qatar; warehouse services Qatar; logistics warehouse Qatar; storage company Qatar; commercial storage Qatar; distribution warehouse Qatar',
    ['3pl-logistics', 'road-freight', 'sea-freight'], 'Services.jsx: warehousing and inventory; specialist temperature/certification claims not independently verified'),
  service('customs-clearance', 'Customs Clearance Services', 'Customs Clearance Services in Qatar', 'customs clearance Qatar',
    'Argus Shipping coordinates customs clearance support for cargo moving to and from Qatar. Discuss documentation and shipment responsibilities before freight is dispatched.', [
      s('Import and export documentation support', 'Start with a clear goods description, shipper and consignee details, commercial invoice information and packing details. The team reviews the shipment scope and identifies documentation to prepare. The final requirements depend on the commodity, origin, destination and applicable procedures.'),
      s('Sea, air and road cargo coordination', 'Customs preparation should align with the freight booking and the arrival gateway. Argus coordinates port, airport and cross-border support. Linking those tasks helps the parties respond to document queries and coordinate release with onward transport.'),
      s('Responsibilities and charges', 'Confirm who will act as the importer or exporter and who is responsible for duties, taxes and any inspection or handling charges. A freight quotation should make inclusions and exclusions clear. Customs release is subject to the relevant authorities; it cannot be guaranteed in advance.'),
      s('Cargo needing additional checks', 'Identify special goods and supporting product information before shipment. The team can discuss the clearance coordination required for your cargo. Confirm the applicable requirements with the operations team before dispatch.'),
    ], 'customs clearance services Qatar; customs clearance company Qatar; customs clearance Doha; import customs clearance Qatar; export customs clearance Qatar; Hamad Port customs clearance; airport customs clearance Qatar',
    ['air-freight', 'sea-freight', 'road-freight'], 'Services.jsx: border support and door-to-door documentation; no licence evidence'),
  service('3pl-logistics', '3PL Logistics Services', '3PL Logistics Services in Qatar', '3PL logistics Qatar',
    'Argus Shipping offers third-party logistics connecting inventory storage, order fulfilment and regional distribution. Businesses can discuss an outsourced logistics scope suited to their stock and delivery requirements.', [
      s('From storage to order fulfilment', 'A 3PL arrangement combines several operating tasks rather than a single storage booking. Define which activities Argus will handle: receipt of stock, inventory records, release against orders and distribution. Clear handover points make responsibilities easier to manage.'),
      s('Inventory and distribution planning', 'Provide your SKU count, order profile, average shipment size and expected peaks. Agree how stock instructions, order information and delivery updates will be exchanged. The required process will differ between bulk replenishment to businesses and small individual orders.'),
      s('Regional logistics outsourcing', 'Argus’s 3PL service includes storage, fulfilment and distribution to commercial networks. Discuss the destination coverage, frequency and delivery conditions needed by your customers. Integration requirements, reporting and service levels should be defined in the proposed operating scope.'),
      s('Prepare a useful 3PL enquiry', 'Include monthly inbound volume, stockholding expectations, order lines and outbound destinations. Identify special handling and return requirements separately. This gives the team a basis for assessing the operating arrangement instead of quoting a generic warehouse space rate.'),
    ], '3PL Qatar; third party logistics Qatar; 3PL company Qatar; contract logistics Qatar; fulfillment services Qatar; logistics outsourcing Qatar; warehouse distribution Qatar; inventory management Qatar; fulfillment Qatar',
    ['warehousing', 'road-freight', 'door-to-door-cargo'], 'Services.jsx: explicit Third-Party Logistics service'),
  service('door-to-door-cargo', 'Door-to-Door Cargo', 'Door-to-Door Cargo Services in Qatar', 'door-to-door cargo Qatar',
    'Argus Shipping coordinates door-to-door cargo for businesses shipping to Qatar. Supplier collection, consolidation, freight and destination delivery can be arranged within an agreed shipment scope.', [
      s('A connected collection-to-delivery journey', 'The journey starts with supplier collection and origin handling, continues through the freight leg and clearance, and ends with delivery to the consignee. Agree each stage when requesting a quotation. Door-to-door describes the physical journey; payment of duties and other charges must still be specified.'),
      s('Consolidation for smaller consignments', 'The Argus service includes carton and cubic-metre consolidation arrangements for smaller volumes. Multiple supplier collections can be discussed to combine compatible goods. Provide the ready dates and package information for each supplier so the team can plan the handover.'),
      s('Choose the freight mode', 'Air and sea freight serve different delivery and volume requirements. For regional cargo, discuss the available road arrangement. Compare the complete scope, including origin collection and destination delivery, rather than only the main freight charge.'),
      s('Prepare for final delivery', 'Share the consignee contact, full address, access restrictions and unloading arrangements. Goods requiring storage before delivery should be identified early. Delivery scheduling depends on freight arrival, release and the receiving location’s availability.'),
    ], 'door to door cargo Qatar; door to door shipping Qatar; door to door freight Qatar; international door to door cargo Qatar; cargo pickup and delivery Qatar; freight delivery Qatar',
    ['air-freight', 'sea-freight', 'customs-clearance'], 'Services.jsx: door-to-door consolidation and supplier collection'),
  service('project-cargo', 'Project Cargo & Heavy Lift', 'Project Cargo & Heavy-Lift Logistics in Qatar', 'project cargo Qatar',
    'Argus Shipping supports heavy-lift transport and project cargo coordination. Discuss the cargo dimensions, handling requirements and delivery site before selecting a transport arrangement.', [
      s('Start with the cargo and site survey information', 'Project enquiries need more than a total shipment weight. Supply piece-by-piece dimensions, weights, drawings and photographs where available. Identify lifting points, centre-of-gravity information and the loading and delivery sites so the team can assess the movement.'),
      s('Oversized cargo and transport options', 'Cargo outside standard transport dimensions requires an individual handling assessment. Road and sea options depend on the piece size, securing requirements and available equipment. Any proposed special container, lifting or route arrangement must be confirmed against the shipment specifications.'),
      s('Coordinate delivery with the project programme', 'A project delivery may depend on site readiness, unloading equipment and an installation sequence. Share those dependencies when planning the movement. Agree the parties responsible for loading, lifting, securing, transport and receipt before dispatch.'),
      s('Request an assessed project quotation', 'Send the origin, destination, cargo-ready date and desired delivery window with the technical cargo information. Argus can review the request with you and define the proposed scope. Equipment and handling arrangements are assessed against the cargo specifications.'),
    ], 'project logistics Qatar; heavy cargo Qatar; heavy lift logistics Qatar; oversized cargo Qatar; OOG cargo Qatar; industrial logistics Qatar; construction project cargo Qatar',
    ['sea-freight', 'road-freight', 'customs-clearance'], 'About.jsx: heavy-lift transport; detailed project credentials still required'),
  service('vehicle-logistics', 'Vehicle Logistics & Car Shipping', 'Vehicle Logistics & Car Shipping Services in Qatar', 'vehicle logistics Qatar',
    'Argus Shipping offers vehicle import and export logistics for dealers and private owners. Discuss the vehicle details, origin and destination to assess a shipping and handling arrangement.', [
      s('Plan a vehicle movement', 'Provide the make, model, dimensions and operating condition of each vehicle. Explain whether the enquiry is for one vehicle or a dealer shipment and identify the collection and delivery locations. Those details affect handling, transport equipment and the proposed scope.'),
      s('Import and export coordination', 'Vehicle movements need shipment documentation and a clear allocation of importer and exporter responsibilities. Requirements depend on the vehicle and destination. Confirm eligibility and required paperwork with the team before arranging collection or committing to a shipment date.'),
      s('Handling, storage and delivery', 'Argus’s vehicle logistics service includes storage and local vehicle movements. Agree the handover condition record, any storage period and final delivery arrangements. Do not leave personal items in the vehicle without first confirming how they will be treated in the shipment.'),
      s('Request a car shipping quotation', 'Send the vehicle details, collection address, destination and preferred schedule. Identify non-running vehicles or modifications that affect handling. The team can explain the available arrangement and the charges included in the quote.'),
    ], 'car shipping Qatar; vehicle shipping Qatar; automobile logistics Qatar; international vehicle shipping Qatar',
    ['customs-clearance', 'sea-freight', 'road-freight'], 'Services.jsx: explicit Finished Vehicle Logistics service'),
];

const lane = (slug, label, h1, keyword, intro, sections, keywords, evidence) => ({
  path: `/shipping/${slug}-to-qatar/`, group: 'shipping', label, h1, keyword, intro, sections,
  title: `${label} Shipping | Argus Shipping`, description: `${intro.split('. ')[0]}. Discuss collection, freight and delivery with Argus Shipping.`,
  keywords: keywords.split('; '), related: ['uae', 'bahrain'].includes(slug) ? ['road-freight', 'door-to-door-cargo', 'customs-clearance', 'warehousing'] : ['air-freight', 'sea-freight', 'door-to-door-cargo', 'customs-clearance', 'warehousing'], evidence, priority: 'P2',
});
export const tradePages = [
  lane('china', 'China to Qatar', 'Shipping from China to Qatar', 'shipping from China to Qatar',
    'Argus Shipping coordinates China-to-Qatar freight through its Guangzhou and Yiwu network. Businesses sourcing from several suppliers can discuss collection, consolidation and delivery requirements alongside air or sea freight.', [
      s('Guangzhou and Yiwu supplier coordination', 'Send each supplier’s address, contact details and cargo-ready date. The Guangzhou and Yiwu locations provide a starting point for discussing origin coordination. Confirm the receiving location and appointment before asking a supplier to deliver cargo.'),
      s('Air freight versus sea freight', 'Air freight can be assessed for urgent or time-sensitive consignments. Sea freight provides FCL and LCL options for containerised cargo. The best fit depends on the delivery requirement, chargeable size and complete handling scope; a timetable is confirmed for the actual booking.'),
      s('FCL, LCL and multi-supplier consolidation', 'For a full container, review the complete loading plan. For smaller consignments, provide package dimensions and supplier-ready dates to discuss consolidation. Multiple suppliers should use consistent product and package references so cargo can be reconciled before onward shipment.'),
      s('Qatar clearance and final delivery', 'Agree the importer details, document preparation and delivery address before dispatch. Discuss warehousing if goods are arriving ahead of the receiving schedule. Ask the quote to separate origin collection, freight, destination handling and any excluded charges.'),
    ], 'China to Qatar shipping; freight from China to Qatar; China to Qatar freight; China to Qatar cargo; cargo from China to Qatar; sea freight China to Qatar; air freight China to Qatar; China to Doha shipping; China to Qatar door-to-door cargo; Guangzhou to Qatar cargo; Guangzhou to Qatar freight; Yiwu to Qatar shipping; China to Qatar LCL shipping; China to Qatar FCL shipping; China to Hamad Port shipping', 'App.jsx: Guangzhou and Yiwu addresses; Services.jsx consolidation network'),
  lane('india', 'India to Qatar', 'Shipping from India to Qatar', 'shipping from India to Qatar',
    'Argus Shipping supports India-to-Qatar cargo through its India network and consolidation service. Businesses can discuss supplier collection, air or sea freight and delivery to the Qatar consignee.', [
      s('Coordinate collection across sourcing locations', 'The India network includes Mumbai and Bangalore consolidation, with contacts in Tuticorin and Nilambur. Provide the actual supplier location so collection and receiving arrangements can be confirmed; a listed office is not automatically a cargo receiving terminal.'),
      s('Air cargo and sea cargo options', 'For air cargo, provide the required arrival date and package weights and dimensions. For sea cargo, discuss whether the volume suits LCL consolidation or an FCL movement. The selected gateway and routing depend on origin location and the available booking.'),
      s('Supplier documentation and packing', 'Ask suppliers for consistent descriptions and package-level quantities before handover. When combining orders, identify which invoice relates to each package. Flag fragile goods, equipment or other handling needs before collection so the proposed packing and transport arrangement can be reviewed.'),
      s('Door-to-door delivery in Qatar', 'Request a scope covering the stages you need, from supplier pickup through destination delivery. Confirm the importer, consignee address and unloading arrangements. Actual scheduling depends on collection readiness, the freight booking and release formalities.'),
    ], 'India to Qatar cargo; India to Qatar freight; freight from India to Qatar; air cargo India to Qatar; sea cargo India to Qatar; India to Qatar door-to-door cargo', 'App.jsx: India contacts; Services.jsx: Mumbai and Bangalore consolidation'),
  lane('uae', 'UAE to Qatar', 'Freight Shipping from UAE to Qatar', 'UAE to Qatar freight',
    'Argus Shipping coordinates UAE-to-Qatar freight through its Dubai network and GCC road service. Businesses can discuss supplier collections, FTL or LTL transport and Qatar delivery.', [
      s('Dubai collection and consolidation', 'Argus lists a Dubai location in Al Qusais Industrial Area 4. Share the collection address and whether goods are at a supplier, warehouse or another facility. The team will confirm the appropriate handover point and any collection formalities before dispatch.'),
      s('Road freight: full and shared loads', 'FTL and LTL options suit different cargo volumes and delivery requirements. Share piece sizes and weights, identify incompatible or fragile cargo, and confirm loading equipment. The quote should state whether collection, cross-border coordination and delivery are included.'),
      s('Cross-border shipment preparation', 'UAE-to-Qatar road freight involves transit and border coordination along the proposed route. Clarify the shipment’s commercial status and documentation responsibilities before loading. Do not assume a warehouse-to-warehouse rate includes every customs, inspection or handling charge.'),
      s('Delivery to Doha and other Qatar destinations', 'Give the full destination address, receiving contact and appointment restrictions. If the delivery site cannot accept the full load at once, discuss a storage or staged distribution requirement with the team. The operating schedule is assessed for each movement.'),
    ], 'Dubai to Qatar cargo; Dubai to Qatar freight; UAE to Qatar shipping; UAE to Qatar road freight; Dubai Doha cargo; door-to-door Dubai Qatar', 'App.jsx: Dubai address; Services.jsx: explicit UAE-to-Qatar FTL/LTL route'),
  lane('turkey', 'Turkey to Qatar', 'Shipping from Turkey to Qatar', 'Turkey to Qatar shipping',
    'Argus Shipping’s Istanbul consolidation network supports Turkey-to-Qatar cargo enquiries. Discuss supplier pickup, shipment consolidation and air or sea freight suited to the order.', [
      s('Istanbul supplier and cargo coordination', 'Provide the supplier’s actual collection address and the cargo-ready date. Istanbul is part of the consolidation network. Receiving instructions and any collection outside the agreed area must be confirmed before a supplier dispatches goods.'),
      s('Air and sea freight from Turkey', 'Air freight can be assessed where delivery timing is the main constraint. Sea freight can be discussed for larger orders and consolidated cargo. Origin handling, routing and the final delivery requirement determine the shipment scope; no fixed transit time is promised.'),
      s('Combining commercial orders', 'When sourcing from multiple suppliers, list each order and its packing details separately. Confirm that all goods will be ready in time for the planned consolidation. Inconsistent descriptions or late supplier handovers can change the proposed movement.'),
      s('Prepare the Qatar receiving arrangement', 'Agree the importer details, required documents and consignee address before booking. Include special handling and unloading requirements in the enquiry. Request a quote that identifies the origin, freight and destination stages and any exclusions.'),
    ], 'Turkey to Qatar cargo; freight Turkey to Qatar; Istanbul to Qatar cargo; Turkey Qatar logistics; air freight Turkey Qatar; sea freight Turkey Qatar', 'Services.jsx: Istanbul consolidation and Turkey maritime table'),
  lane('bahrain', 'Bahrain to Qatar', 'Freight Shipping from Bahrain to Qatar', 'Bahrain to Qatar freight',
    'Argus Shipping’s Bahrain office and GCC network support Bahrain-to-Qatar cargo coordination. Discuss collection, cross-border road freight and the delivery requirements for your consignment.', [
      s('Bahrain collection planning', 'Argus lists a Bahrain office in Busaiteen. Provide the cargo collection address separately: an office location is not necessarily a cargo receiving facility. Confirm the booking and receiving instructions with the team before sending goods.'),
      s('Regional road freight coordination', 'Road cargo between Bahrain and Qatar requires a route and transit plan across the regional network. The operating arrangement depends on the cargo and current booking conditions. Ask whether the proposed service is a full-load or consolidated movement and how handovers will be managed.'),
      s('Documents and loading requirements', 'Provide the commercial cargo description, packing details, origin contact and consignee information. Identify goods requiring particular securing or handling arrangements. Agree document responsibilities and the scope of border support before the vehicle is scheduled.'),
      s('Receiving cargo in Qatar', 'Include the receiving hours, unloading equipment and access restrictions at the destination. If stock will be stored or distributed after arrival, discuss that requirement as part of the enquiry. The team can assess the schedule once cargo readiness and route arrangements are known.'),
    ], 'Bahrain to Qatar cargo; Bahrain Qatar road freight; shipping Bahrain to Qatar', 'App.jsx: Bahrain office; Services.jsx: Bahrain consolidation and GCC network'),
];
export const commercialPages = [...servicePages, ...tradePages];
export const byPath = Object.fromEntries(commercialPages.map(page => [page.path, page]));
export const serviceById = Object.fromEntries(servicePages.map(page => [page.path.split('/')[2].replace(/-qatar$/, ''), page]));
export const serviceLinks = Object.fromEntries(Object.entries({ air: 'air-freight', sea: 'sea-freight', road: 'road-freight', warehouse: 'warehousing', warehousing: 'warehousing', doortodoor: 'door-to-door-cargo', 'door-to-door': 'door-to-door-cargo', '3pl': '3pl-logistics', vehicle: 'vehicle-logistics' }).map(([id, slug]) => [id, serviceById[slug].path]));
export function normalizePath(path) {
  const clean = path.replace(/\.html$/, '').replace(/\/$/, '') || '/';
  return byPath[`${clean}/`] || clean === '/shipping' ? `${clean}/` : clean;
}
