// frontend/lib/countries.ts
export const COUNTRIES = [
  "Qatar",
  "United Arab Emirates",
  "Saudi Arabia",
  "Kuwait",
  "Oman",
  "Bahrain",
  "India",
  "Turkey",
  "Germany",
  "United Kingdom",
  "United States",
  "China",
  "Singapore",
  "Malaysia",
  "Egypt",
  "Jordan",
  "Lebanon",
  "Pakistan",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Canada",
  "Australia",
  "New Zealand",
  "Japan",
  "South Korea",
  "Vietnam",
  "Indonesia",
  "Thailand",
  "Brazil",
  "South Africa"
];
